In [1]:
import pandas as pd

In [2]:
all_data = pd.read_csv("cumulative_processed_data_22.csv")
all_data.head()

,Unnamed: 0,Date,Age,Game Result,GS,MP,FG,FGA,FGcent,3P,...,BLK,TOV,PF,PTS,GmSc,PointDifference,Player,2P,2PA,2Pcent
0,0,10/19/2022,26.082192,W,1,38.233333,8,19,0.421,1,...,1,0,0,20,24.8,8.0,Dejounte Murray,7,14,0.500000
1,1,10/21/2022,26.087671,W,1,39.616667,8,16,0.500,2,...,0,7,2,20,17.6,17.0,Dejounte Murray,6,11,0.545455
2,2,10/23/2022,26.093151,L,1,38.800000,7,15,0.467,2,...,1,4,2,19,14.5,-11.0,Dejounte Murray,5,11,0.454545
3,3,10/26/2022,26.101370,W,1,39.316667,5,18,0.278,2,...,2,2,2,14,12.0,4.0,Dejounte Murray,3,12,0.250000
4,4,10/28/2022,26.106849,W,1,32.383333,12,21,0.571,2,...,0,0,0,26,20.8,21.0,Dejounte Murray,10,15,0.666667

In [4]:
#find all players
all_players = all_data['Player'].unique()

465

In [43]:

player_averages = pd.DataFrame(columns=['Age','GS','MP','FG','FGA','FGcent','3P','3PA','3Pcent','2P','2PA','2Pcent','FT','FTA','FTcent','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','GmSc','PointDifference','Player'])
player_std = pd.DataFrame(columns=['Age','GS','MP','FG','FGA','FGcent','3P','3PA','3Pcent','2P','2PA','2Pcent','FT','FTA','FTcent','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','GmSc','PointDifference','Player'])

i = 0
for player in all_players:
  player_data = all_data[all_data['Player']==player]
  player_averages.loc[i] = player_data.mean(numeric_only=True)
  player_averages.at[i,"Player"] = player

  player_std.loc[i] = player_data.std(numeric_only = True)
  player_std.at[i,"Player"] = player
  i+=1

player_averages["stat"] = "avg"
player_std["stat"] = "std"

In [47]:

frames = [player_averages,player_std]
player_stats_combined =pd.concat(frames,)
player_stats_combined.columns=player_stats_combined.columns.str.replace("3","Three")
player_stats_combined.columns=player_stats_combined.columns.str.replace("2","Two")
player_stats_combined.rename(columns={"Player":"PlayerName"},inplace=True)
player_stats_combined.to_csv("player_stats_combined_22.csv",index=False)
#be sure to add "stat" at the top of the columns that avg, str.
player_stats_combined.head(10)

,Age,GS,MP,FG,FGA,FGcent,ThreeP,ThreePA,ThreePcent,TwoP,...,AST,STL,BLK,TOV,PF,PTS,GmSc,PointDifference,PlayerName,stat
0,26.135616,1.000000,36.637500,8.250000,18.750000,0.433150,2.000000,5.950000,0.315300,6.250000,...,6.650000,1.950000,0.300000,2.400000,1.650000,20.750000,16.625000,0.700000,Dejounte Murray,avg
1,25.124658,1.000000,32.187500,4.850000,9.950000,0.479900,0.750000,3.350000,0.265000,4.100000,...,1.250000,0.800000,1.300000,1.500000,3.300000,12.600000,9.995000,0.500000,John Collins,avg
2,20.889041,0.000000,13.296667,1.800000,3.800000,0.519167,0.250000,1.300000,0.178571,1.550000,...,0.700000,0.700000,0.300000,0.450000,1.450000,4.350000,3.715000,-0.200000,Jalen Johnson,avg
3,24.135689,1.000000,35.489474,8.947368,22.105263,0.401000,2.315789,7.368421,0.321263,6.631579,...,9.368421,0.842105,0.157895,3.526316,1.526316,28.210526,20.568421,1.368421,Trae Young,avg
4,24.930930,1.000000,31.923684,5.526316,12.684211,0.433053,1.368421,4.052632,0.342053,4.157895,...,1.052632,0.368421,0.157895,1.368421,3.105263,15.421053,8.657895,0.684211,De'Andre Hunter,avg
5,21.907570,0.105263,21.107018,3.157895,5.052632,0.594833,0.000000,0.105263,0.000000,3.157895,...,1.000000,0.578947,0.842105,0.736842,3.000000,7.578947,7.794737,-2.157895,Onyeka Okongwu,avg
6,26.102668,0.052632,17.848246,1.736842,4.210526,0.401611,0.631579,1.368421,0.470214,1.105263,...,1.473684,0.684211,0.157895,0.789474,1.842105,4.526316,3.121053,-0.368421,Aaron Holiday,avg
7,28.469711,1.000000,27.269444,5.055556,8.333333,0.594111,0.000000,0.000000,NaN,5.055556,...,0.833333,0.611111,1.611111,0.944444,2.111111,11.055556,12.722222,1.444444,Clint Capela,avg
8,33.586463,0.000000,16.618627,1.941176,5.235294,0.319125,1.176471,3.705882,0.272125,0.764706,...,0.941176,0.235294,0.294118,0.529412,1.647059,5.058824,2.388235,-1.823529,Justin Holiday,avg
9,19.213014,0.062500,17.653125,3.437500,7.125000,0.450750,1.437500,3.687500,0.437067,2.000000,...,0.750000,0.937500,0.062500,0.687500,1.125000,8.750000,6.431250,-1.125000,AJ Griffin,avg